INSERT INTO tb_game_list (name) VALUES ('Aventura e RPG');
INSERT INTO tb_game_list (name) VALUES ('Jogos de plataforma');

INSERT INTO tb_game(title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Mass Effect Trilogy', 4.8, 2012, 'Role-playing (RPG), Shooter', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/1.png', 'Uma jornada épica onde escolhas moldam o destino da galáxia, com ação intensa e profundidade narrativa.', 'A trilogia Mass Effect segue o Comandante Shepard em uma missão galáctica para enfrentar uma ameaça antiga. Suas decisões afetam personagens, alianças e o universo ao longo de três jogos, combinando ação e exploração com um enredo cativante.');
INSERT INTO tb_game(title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Red Dead Redemption 2', 4.7, 2018, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/2.png', 'Explore o Velho Oeste em um mundo aberto imersivo, onde cada decisão impacta a narrativa e seus relacionamentos.', 'Red Dead Redemption 2 conta a história de Arthur Morgan, um fora da lei tentando sobreviver em uma era de mudança. Com gráficos impressionantes e uma narrativa profunda, o jogo envolve o jogador em decisões morais e interações ricas com o ambiente e personagens.');
INSERT INTO tb_game(title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('The Witcher 3: Wild Hunt', 4.7, 2014, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/3.png', 'Assuma o papel de Geralt de Rivia, um caçador de monstros, em uma busca épica para encontrar sua filha desaparecida em um vasto mundo de fantasia.', 'The Witcher 3: Wild Hunt combina uma narrativa rica com escolhas morais complexas e batalhas desafiadoras, enquanto você explora um mundo aberto vibrante, cheio de criaturas e segredos à espera de serem descobertos.');
INSERT INTO tb_game(title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Sekiro: Shadows Die Twice', 3.8, 2019, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/4.png', 'Embrenhe-se no Japão feudal como um guerreiro destemido, em busca de vingança e honra, enfrentando inimigos formidáveis.', 'Em Sekiro: Shadows Die Twice, você controla um shinobi em uma jornada de vingança e descoberta, em um mundo imersivo e desafiador onde a precisão e estratégia são essenciais para sobreviver.');
INSERT INTO tb_game(title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Ghost of Tsushima', 4.6, 2012, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/5.png', 'Explore o Japão feudal e defenda sua ilha dos invasores mongóis em uma jornada épica de honra e sacrifício.', 'Em Ghost of Tsushima, você se torna Jin Sakai, um guerreiro em busca de justiça contra os invasores. Mergulhe em combates intensos e um mundo vibrante e detalhado inspirado na cultura japonesa.');

INSERT INTO tb_game(title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Super Mario World', 4.7, 1990, 'Platform', 'Super Ness, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/6.png', 'Mario embarca em uma aventura para salvar a Princesa Toadstool das garras de Bowser, explorando o mundo dinâmico de Dinosaur Land.', 'Super Mario World apresenta novos inimigos, amigos e habilidades, como o dinossauro Yoshi e o Cape Feather. Descubra segredos e caminhos ocultos em níveis diversificados e desafiadores nesta clássica aventura de plataforma.');
INSERT INTO tb_game(title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Hollow Knight', 4.6, 2017, 'Platform', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/7.png', 'Explore o misterioso e vasto reino de Hallownest, enfrentando criaturas e revelando segredos em cavernas sombrias.', 'Hollow Knight é um jogo de ação e aventura em estilo Metroidvania. Com uma rica narrativa e belos visuais, você explora um mundo sombrio, combate inimigos e descobre segredos ocultos, imerso em uma experiência desafiadora.');
INSERT INTO tb_game(title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Ori and the Blind Forest', 4, 2015, 'Platform', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/8.png', 'An emotionally charged, hand-painted action-platformer, exploring themes of love, hope, and loss in a mystical forest.', 'Ori and the Blind Forest is a visually stunning action-platformer. Players control Ori, a small guardian spirit, on a journey to save the forest of Nibel. The game features challenging platforming, exploration, and puzzles, paired with a heartfelt story about love, sacrifice, and family.');
INSERT INTO tb_game(title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Cuphead', 4.6, 2017, 'Platform', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/9.png', 'Cuphead is a challenging platformer inspired by 1930s cartoons, known for its unique art style, difficult boss battles, and nostalgic gameplay.', 'Cuphead is a run-and-gun action platformer where players control Cuphead, who must defeat various bosses to repay a debt to the devil. The game features a distinct 1930s cartoon aesthetic, intense difficulty, and fast-paced gameplay. Players explore imaginative worlds, collect power-ups, and face off against creatively designed enemies in epic, multi-phase boss fights.'); 
INSERT INTO tb_game(title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Sonic CD', 4, 1993, 'Platform', 'Sega CD, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/10.png', 'Sonic CD is a fast-paced platformer where Sonic travels through time to defeat Dr. Robotnik and save Amy Rose, featuring vibrant graphics and time manipulation mechanics.', 'Sonic CD is a beloved entry in the Sonic franchise, where Sonic the Hedgehog must travel through time to stop Dr. Robotnik from altering history. The game introduces time travel mechanics, allowing players to explore different versions of each level. With vibrant graphics, a catchy soundtrack, and the addition of Sonic’s friend Amy Rose, Sonic CD remains a classic in the platforming genre.'); 

INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 1, 0);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 2, 1);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 3, 2);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 4, 3);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 5, 4);

INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 6, 0);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 7, 1);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 8, 2);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 9, 3);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 10, 4);
